[package]
name = "shrink_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
shrink.workspace = true

syn = { version = "2.0.72", features = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.86"